import { Injectable } from '@angular/core';
import {SelectItem} from "primeng/primeng";

@Injectable()
export class CurrenciesService {

  currencies: SelectItem[];
  constructor() { }

  initCurrencies()
  {
    this.currencies = [
      {label:'PLN', value:"zł"},
      {label:'USD', value:"$"},
      {label:'EUR', value:"€"},
      {label:'JPY', value:"¥"},
      {label:'GBP ', value:"£"},
      {label:'AUD ', value:"$"},
      {label:'CAD', value:"$"},
      {label:'CHF', value:"Fr"},
      {label:'CNY', value:"元"},
      {label:'SEK', value:"kr"},
      {label:'NZD', value:"$"},
      {label:'MXN', value:"$"},
      {label:'SGD', value:"$"},
      {label:'HKD', value:"$"},
      {label:'NOK', value:"kr"},
      {label:'KRW', value:"₩"},
      {label:'TRY', value:"₺"},
      {label:'RUB', value:"₽"},
      {label:'INR', value:"₹"},
      {label:'BRL', value:"$"},
      {label:'ZAR', value:"R"},
      {label:'AED', value:"د.إ.‏"},
      {label:'AFN', value:"؋"},
      {label:'ALL', value:"Lek"},
      {label:'AMD', value:"դր."},
      {label:'ARS', value:"$"},
      {label:'AZN', value:"ман."},
      {label:'BAM', value:"KM"},
      {label:'BDT', value:"৳"},
      {label:'BGN', value:"лв."},
      {label:'BHD', value:"د.ب."},
      {label:'BIF', value:"FBu"},
      {label:'BND', value:"$"},
      {label:'BOB', value:"Bs"},
      {label:'BWP', value:"P"},
      {label:'BYR', value:"BYR"},
      {label:'BZD', value:"$"},
      {label:'CDF', value:"FrCD"},
      {label:'CLP', value:"$"},
      {label:'COP', value:"$"},
      {label:'CRC', value:"₡"},
      {label:'CVE', value:"CV$"},
      {label:'CZK', value:"Kč"},
      {label:'DJF', value:"Fdj"},
      {label:'DKK', value:"kr"},
      {label:'DOP', value:"RD$"},
      {label:'DZD', value:"د.ج."},
      {label:'EEK', value:"kr"},
      {label:'EGP', value:"ج.م."},
      {label:'ERN', value:"Nfk"},
      {label:'ETB', value:"Br"},
      {label:'GEL', value:"GEL"},
      {label:'GHS', value:"GH₵"},
      {label:'GNF', value:"FG"},
      {label:'GTQ', value:"Q"},
      {label:'HNL', value:"L"},
      {label:'HRK', value:"kn"},
      {label:'HUF', value:"Ft"},
      {label:'IDR', value:"Rp"},
      {label:'ILS', value:"₪"},
      {label:'IQD', value:"د.ع."},
      {label:'IRR', value:"﷼"},
      {label:'ISK', value:"kr"},
      {label:'JMD', value:"$"},
      {label:'JOD', value:"د.أ."},
      {label:'KES', value:"Ksh"},
      {label:'KHR', value:"៛"},
      {label:'KMF', value:"FC"},
      {label:'KWD', value:"د.ك."},
      {label:'KZT', value:"тңг."},
      {label:'LBP', value:"ل.ل."},
      {label:'LKR', value:"SL Re"},
      {label:'LTL', value:"Lt"},
      {label:'LVL', value:"Ls"},
      {label:'LYD', value:"د.ل."},
      {label:'MAD', value:"د.م.‏"},
      {label:'MDL', value:"MDL"},
      {label:'MGA', value:"MGA"},
      {label:'MKD', value:"MKD"},
      {label:'MMK', value:"K"},
      {label:'MOP', value:"MOP$"},
      {label:'MUR', value:"MURs"},
      {label:'MYR', value:"RM"},
      {label:'MZN', value:"MTn"},
      {label:'NAD', value:"N$"},
      {label:'NGN', value:"₦"},
      {label:'NIO', value:"C$"},
      {label:'NPR', value:"नेरू"},
      {label:'OMR', value:"ر.ع."},
      {label:'PAB', value:"B/."},
      {label:'PEN', value:"S/."},
      {label:'PHP', value:"₱"},
      {label:'PKR', value:"₨"},
      {label:'PYG', value:"₲"},
      {label:'QAR', value:"ر.ق."},
      {label:'RON', value:"RON"},
      {label:'RSD', value:"руб."},
      {label:'RWF', value:"FR"},
      {label:'SAR', value:"ر.س."},
      {label:'SDG', value:"SDG"},
      {label:'SOS', value:"Ssh"},
      {label:'SYP', value:"ل.س."},
      {label:'THB', value:"฿"},
      {label:'TND', value:"د.ت."},
      {label:'TOP', value:"T$"},
      {label:'TTD', value:"$"},
      {label:'TWD', value:"$"},
      {label:'TZS', value:"TSh"},
      {label:'UAH', value:"₴"},
      {label:'UGX', value:"USh"},
      {label:'UYU', value:"$"},
      {label:'UZS', value:"UZS"},
      {label:'VEF', value:"Bs.F."},
      {label:'VND', value:"₫"},
      {label:'XAF', value:"FCFA"},
      {label:'XOF', value:"CFA"},
      {label:'YER', value:"ر.ي."},
      {label:'ZMK', value:"ZK"},
    ];
  }

  getCurrencies()
  {
    if(!this.currencies)
    {
      this.initCurrencies();
    }
    return this.currencies;
  }
}
